# channels can be in different namespaces
# from the subscription
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: nginx-simple-subscription
  namespace: nginx-simple
  annotations:
    apps.open-cluster-management.io/github-path: nginx/deployment
    apps.open-cluster-management.io/github-branch: master
  labels:
    app: nginx-simple
spec:
  channel: nginx-simple/nginx-simple
  placement:
    placementRef:
      name: nginx-simple
      kind: PlacementRule
