---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: nginx-simple-5
  namespace: nginx-simple-5
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx-simple
